version: '3'
services:
  web:
    container_name: sample-spa-nuxt
    build:
      context: ./.docker/web
      dockerfile: Dockerfile
    environment:
      PORT: '3000'
      HOST: '0.0.0.0'
      BASE_URL: 'http://nginx'
    ports:
      - 3000:3000
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    restart: always
    networks:
      - sample-spa

networks:
  sample-spa:
    external: true
